apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: 
       app: nginx
    spec:
      contianers:
        - name: nginx
          image: nginx:latest
          containerPort: 8082
---
apiVersion: v1
type: Service
metadata:
   name: nginx-service
spec:
   selector:
     app: nginx 
   ports:
     - protocol: TCP
       port: 80
       targetPort: 8082
              
          
        